networks:
  gym-network:

services:

  membership-service:
    container_name: membership-service
    build: .
    restart: unless-stopped
    ports:
      - ${MEMBERSHIP_SERVICE_PORT}:8080
    env_file:
      - path: ./default.env
        required: true
    networks:
      - gym-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:18-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d $POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - path: ./default.env
        required: true
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - gym-network

  redis:
    container_name: redis
    image: redis:8.4.0-alpine
    env_file:
      - path: ./default.env
        required: true
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - gym-network
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    restart: unless-stopped
    stdin_open: true
    tty: true

  kafka:
    container_name: kafka
    image: apache/kafka:4.0.1
    env_file:
      - path: ./default.env
        required: true
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092 || exit -1
    ports:
      - ${KAFKA_PORT}:9092
    networks:
      - gym-network
